/*
 * MenuPage.java
 *
 * Created on 22 May, 2020, 2:02 AM
 */

package tictactoe;

/**
 *
 * @author  KaranRajpara
 */
public class MenuPage extends javax.swing.JFrame {
    
    /** Creates new form MenuPage */
    public MenuPage() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
       
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_player2 = new javax.swing.JTextField();
        jTextField_player1 = new javax.swing.JTextField();
        jButton_exit = new javax.swing.JButton();
        jButton_start = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 48));
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("Tic Tac Toe");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(540, 30, 275, 64);

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24));
        jLabel2.setText("Enter player 2 Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 340, 280, 50);

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 24));
        jLabel3.setText("Enter player 1 Name :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 180, 280, 50);

        jTextField_player2.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jTextField_player2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField_player2);
        jTextField_player2.setBounds(560, 350, 350, 40);

        jTextField_player1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jTextField_player1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextField_player1);
        jTextField_player1.setBounds(560, 190, 350, 40);

        jButton_exit.setBackground(new java.awt.Color(204, 0, 0));
        jButton_exit.setFont(new java.awt.Font("SansSerif", 0, 24));
        jButton_exit.setText("Exit");
        jButton_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_exitActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_exit);
        jButton_exit.setBounds(1100, 590, 130, 50);

        jButton_start.setBackground(new java.awt.Color(0, 204, 102));
        jButton_start.setFont(new java.awt.Font("SansSerif", 0, 24));
        jButton_start.setText("Start Game");
        jButton_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_startActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_start);
        jButton_start.setBounds(560, 480, 170, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_startActionPerformed
        // TODO add your handling code here:
       String player1=jTextField_player1.getText();
       String player2=jTextField_player2.getText();
       if(player1.equals(""))
       {
           player1="Player 1";
       }
       if(player2.equals(""))
       {
           player2="Player 2";
       }
       Game showname=new Game();
       showname.displayName(player1, player2);
      new Game().setVisible(true);
       this.setVisible(false);
       
    }//GEN-LAST:event_jButton_startActionPerformed

    private void jButton_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_exitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton_exitActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPage().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_exit;
    private javax.swing.JButton jButton_start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField_player1;
    private javax.swing.JTextField jTextField_player2;
    // End of variables declaration//GEN-END:variables
    
}
